### ISSUE TITLE
kanpig error

### ISSUE THREAD

**Issue by coopsor** [ACEnglish/kanpig#3]
Thank you for developing such an excellent tool. However, I encountered the following error while running kanpig on the tier1 benchmark VCF released by GIAB. I was able to successfully test it using sniffles-fc. It seems that the VCF file does not meet kanpig's input specifications. Could you please advise me on how to resolve this issue? 
I am running the latest version of kanpig, and the link to the HG002_SVs_Tier1_v0.6.vcf file is: [https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/NIST_SVs_Integration_v0.6/](url)

![b99213ad5fbf2d596f199c6ca6647c5](https://github.com/user-attachments/assets/f0e5f897-c17a-48b3-878f-249ad33b36c2)

**Comment by ACEnglish** [comment]
Hello,

This error is telling us that the header is malformed due to a Duplicate Info Id "BREAKSIMLENGTH". Manual inspection of the vcf confirms this is indeed an error. I was able to fix it by running

`bcftools annotate -x INFO/BREAKSIMLENGTH HG002_SVs_Tier1_v0.6.vcf.gz -O z -o fixed.vcf.gz`

Note that this error is due to kanpig's use off noodles_vcf as its vcf parser, which has excellent adherence to the VCF format specification, meaning the issue needs to be resolved by the maintainers of the VCF. Therefore, there will be no change to kanpig to handle non-standard VCFs.

Also, as mentioned in the [kanpig preprint](https://www.biorxiv.org/content/10.1101/2024.10.22.619642v1), the GIAB v0.6 benchmark is somewhat incomplete relative to the newer [draft GIAB v1.1](https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/NIST_HG002_DraftBenchmark_defrabbV0.019-20241113/). Just intersecting these two benchmarks with `truvari bench -b HG002_SVs_Tier1_v0.6.vcf.gz --includebed HG002_SVs_Tier1_v0.6.bed -c GRCh37_HG2-T2TQ100-V1.1_stvar.vcf.gz -o sv1 --passonly` shows that the genotypes of v0.6 are of lower quality than v1.1. So I'm unsure what kind of performance you'll see from kanpig on that v0.6.

```
    "precision": 0.7816, # v1.1 in v0.6
    "recall": 0.9730,  # v0.6 in v1.1
    "gt_concordance": 0.8335, # matched variants' concordance
```

Have a great day,
~/Adam English

**Comment by coopsor** [comment]
This test was merely to evaluate kanpig's performance on traditional datasets. Based on your guidance, I successfully tested kanpig on GIAB v0.6. The results indicate that compared to the traditional genotyping tool Sniffles-FC, kanpig demonstrates a more pronounced advantage of genotype concordanc on GIAB v1.1: 78.3 vs 61.4 for v1.1, and 86.9 vs 95.3 for v0.6 (kanpig vs Sniffles-FC). Kanpig 's genotyping results are closer to those of assembly-based approaches, which I believe is a significant finding in the context of assembly results becoming a popular evaluation trend.
